# Site settings
title: trial and error
description: > # this means to ignore newlines until "baseurl:"
  Kilian's blog 'n stuff. Sounds about right.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.kilian.io" # the base hostname & protocol for your site
highlighter: pygments
paginate: 8
header-img: "img/home-bg.jpg"
permalink: /:title/

# Personal settings
author: Kilian Koeltzsch
author_short: Kilian
email: me@kilian.io
twitter_username: kiliankoe
github_username:  kiliankoe

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
