# Site settings
title: trial and error
email: me@kilian.io
description: > # this means to ignore newlines until "baseurl:"
  Kilian's blog 'n stuff. Sounds about right.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.kilian.io" # the base hostname & protocol for your site
author: Kilian Koeltzsch
permalink: /:title/
twitter_username: kiliankoe
github_username:  kiliankoe

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
